/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Calculater extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Calculater() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cmbShape = new javax.swing.JComboBox<>();
        rdoPer = new javax.swing.JRadioButton();
        rdoArea = new javax.swing.JRadioButton();
        txtOutput = new javax.swing.JTextField();
        txtOne = new javax.swing.JTextField();
        txtTwo = new javax.swing.JTextField();
        txtThree = new javax.swing.JTextField();
        lblOne = new javax.swing.JLabel();
        lblTwo = new javax.swing.JLabel();
        lblThree = new javax.swing.JLabel();
        txtFour = new javax.swing.JTextField();
        lblFour = new javax.swing.JLabel();
        txtFive = new javax.swing.JTextField();
        lblFive = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbShape.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Shape","Square", "Rectangle", "Triangle", "Circle", "Semicircle", "Paralleogram","Rhombus"}));
        cmbShape.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbShapeActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoPer);
        rdoPer.setText("Perimeter");
        rdoPer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoPerActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoArea);
        rdoArea.setText("Area");
        rdoArea.setContentAreaFilled(false);
        rdoArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAreaActionPerformed(evt);
            }
        });

        txtOutput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtOne.setEnabled(false);

        txtTwo.setEnabled(false);

        txtThree.setEnabled(false);

        txtFour.setEnabled(false);

        txtFive.setEnabled(false);

        btnclear.setText("Clear");
        btnclear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblOne, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblFour, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblFive, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblThree, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(rdoPer)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(rdoArea))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtThree, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFour, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnclear)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cmbShape, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtThree)
                    .addComponent(lblThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFour, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFive, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoArea)
                    .addComponent(rdoPer))
                .addGap(18, 18, 18)
                .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnclear)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbShapeActionPerformed

String strType = cmbShape.getSelectedItem().toString();
if(strType == "Square"){
    
lblOne.setText("Enter the value of Side : ");
lblTwo.setText("");
lblThree.setText("");
txtOne.setEnabled(true);
txtTwo.setEnabled(false);
txtThree.setEnabled(false);

}


 if(strType == "Rectangle"){
lblOne.setText("Enter the value of Width : ");
lblTwo.setText("Enter the value of Length : ");
lblThree.setText("");
lblFour.setText("");
lblFive.setText("");
txtOne.setEnabled(true);
txtTwo.setEnabled(true);
txtThree.setEnabled(false);
 txtFour.setEnabled(false);
txtFive.setEnabled(false);}

if(strType == "Triangle"){
lblOne.setText("Enter the value of Side 1 : ");
lblTwo.setText("Enter the value of Side 2 : ");
lblThree.setText("Enter the value of Side 3 : ");
lblFour.setText("Enter the value of Base : ");
lblFive.setText("Enter the value of Height : ");
txtOne.setEnabled(true);
txtTwo.setEnabled(true);
txtThree.setEnabled(true);
txtFour.setEnabled(true);
txtFive.setEnabled(true);}

if(strType == "Circle"){
lblOne.setText("Enter the value of Radius : ");
lblTwo.setText("");
lblThree.setText("");
lblFour.setText("");
lblFive.setText("");
txtOne.setEnabled(true);
txtTwo.setEnabled(false);
txtThree.setEnabled(false);
txtFour.setEnabled(false);
txtFive.setEnabled(false);

}

if(strType == "Semicircle"){
lblOne.setText("Enter the value of Radius : ");
lblTwo.setText("");
lblThree.setText("");
lblFour.setText("");
lblFive.setText("");
txtOne.setEnabled(true);
txtTwo.setEnabled(false);
txtThree.setEnabled(false);
txtFour.setEnabled(false);
txtFive.setEnabled(false);
}

if(strType == "Paralleogram"){
lblOne.setText("Enter the value of Base : ");
lblTwo.setText("Enter the value of Side : ");
lblThree.setText("Enter the value of Height : ");
lblFour.setText("");
lblFive.setText("");
txtOne.setEnabled(true);
txtTwo.setEnabled(true);
txtThree.setEnabled(true);
txtFour.setEnabled(false);
txtFive.setEnabled(false);}

if(strType == "Rhombus"){
    
lblOne.setText("Enter the value of Side : ");
lblTwo.setText("Enter the value of Diagonal 1");
lblThree.setText("Enter the value of Diagonal 2");
lblFour.setText("");
lblFive.setText("");
txtOne.setEnabled(true);
txtTwo.setEnabled(true);
txtThree.setEnabled(true);
txtFour.setEnabled(false);
txtFive.setEnabled(false);

}

    }//GEN-LAST:event_cmbShapeActionPerformed


    private void rdoPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoPerActionPerformed



String strType = cmbShape.getSelectedItem().toString();
if(strType == "Square"){
double  output;
double input= Double.parseDouble(txtOne.getText());
txtOutput.setText("");
output=input*4;
txtOutput.setText(String.valueOf(output));}

 if(strType == "Rectangle"){
 double  output;
double width= Double.parseDouble(txtOne.getText());
double length= Double.parseDouble(txtTwo.getText());
txtOutput.setText("");
output=(width+width+length+length);
txtOutput.setText(String.valueOf(output));}
 
 if(strType == "Circle"){
double  output;
double radius= Double.parseDouble(txtOne.getText());
txtOutput.setText("");
output=radius*2*3.14159;
txtOutput.setText(String.valueOf(output));}
 
  if(strType == "Semicircle"){
double  output;
double radius= Double.parseDouble(txtOne.getText());
txtOutput.setText("");
output=(radius*3.14159)+(2*radius);
txtOutput.setText(String.valueOf(output));}
  
    if(strType == "Triangle"){
double  output;
double side1= Double.parseDouble(txtOne.getText());
double side2= Double.parseDouble(txtTwo.getText());
double side3= Double.parseDouble(txtThree.getText());
txtOutput.setText("");
output=side1+side2+side3;
txtOutput.setText(String.valueOf(output));}
    
    if(strType == "Paralleogram"){
double  output;
double base= Double.parseDouble(txtOne.getText());
double side= Double.parseDouble(txtTwo.getText());
txtOutput.setText("");
output=side+side+base+base;
txtOutput.setText(String.valueOf(output));}
    
    if(strType == "Rhombus"){
double  output;
double input= Double.parseDouble(txtOne.getText());
txtOutput.setText("");
output=input*4;
txtOutput.setText(String.valueOf(output));}
    }//GEN-LAST:event_rdoPerActionPerformed

    private void rdoAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAreaActionPerformed


        String strType = cmbShape.getSelectedItem().toString();

if(strType == "Square"){
double  output;
double input= Double.parseDouble(txtOne.getText());
txtOutput.setText("");
output=input*input;
txtOutput.setText(String.valueOf(output));}

 if(strType == "Rectangle"){
 double  output;
double width= Double.parseDouble(txtOne.getText());
double length= Double.parseDouble(txtTwo.getText());
txtOutput.setText("");
output=(width*length);
txtOutput.setText(String.valueOf(output));}
 
  if(strType == "Circle"){
double  output;
double radius= Double.parseDouble(txtOne.getText());
txtOutput.setText("");
output=(radius*radius)*3.14159;
txtOutput.setText(String.valueOf(output));}
  
    if(strType == "Semicircle"){
double  output;
double radius= Double.parseDouble(txtOne.getText());
txtOutput.setText("");
output=((radius*radius)*3.14159)/2;
txtOutput.setText(String.valueOf(output));}
    
        if(strType == "Triangle"){
double  output;
double base= Double.parseDouble(txtFour.getText());
double height= Double.parseDouble(txtFive.getText());
txtOutput.setText("");
output=(base*height)/2;
txtOutput.setText(String.valueOf(output));}
        
            if(strType == "Paralleogram"){
double  output;
double base= Double.parseDouble(txtOne.getText());
double height= Double.parseDouble(txtThree.getText());
txtOutput.setText("");
output=base*height;
txtOutput.setText(String.valueOf(output));}
            
            if(strType == "Rhombus"){
double  output;
double diagonal1= Double.parseDouble(txtTwo.getText());
double diagonal2= Double.parseDouble(txtThree.getText());
txtOutput.setText("");
output=(diagonal1*diagonal2)/2;
txtOutput.setText(String.valueOf(output));}
    }//GEN-LAST:event_rdoAreaActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
txtOne.setText("");
txtTwo.setText("");
txtThree.setText("");
txtFour.setText("");
txtFive.setText("");
txtOutput.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculater().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbShape;
    private javax.swing.JLabel lblFive;
    private javax.swing.JLabel lblFour;
    private javax.swing.JLabel lblOne;
    private javax.swing.JLabel lblThree;
    private javax.swing.JLabel lblTwo;
    private javax.swing.JRadioButton rdoArea;
    private javax.swing.JRadioButton rdoPer;
    private javax.swing.JTextField txtFive;
    private javax.swing.JTextField txtFour;
    private javax.swing.JTextField txtOne;
    private javax.swing.JTextField txtOutput;
    private javax.swing.JTextField txtThree;
    private javax.swing.JTextField txtTwo;
    // End of variables declaration//GEN-END:variables
}
